"""
DevOps Knowledge Hub - Gemini AI Engine
Integrates Google Gemini 3.8 Flash High exclusively for:
1. Interview Transcript Generation from Audio & Video (Client-side / Ephemeral, zero server disk storage)
2. YouTube Video Transcript & Q&A Extraction
3. Complete Question, Sub-question, and Instructor Suggestion Extraction
4. AI Grammar Review & Text Polish (with Original Raw Text Preservation)
"""

import os
import re
import json
import base64
import logging
import urllib.parse
from typing import Dict, Any, List, Optional
import requests

logger = logging.getLogger("GeminiAIEngine")

# Supported models - strictly limited to 3.8 flash high
DEFAULT_MODELS = [
    "gemini-3.8-flash-high"
]

def resolve_gemini_api_key(client_key: Optional[str] = None) -> str:
    """
    Resolves the Gemini API key from:
    1. Client-supplied key (via header or request body)
    2. Server environment variable GEMINI_API_KEY
    3. Persistent token file on server (/app/data/notes/.gemini_api_key)
    """
    if client_key and client_key.strip():
        return client_key.strip()

    env_key = os.getenv("GEMINI_API_KEY", "").strip()
    if env_key:
        return env_key

    # Check file locations
    candidate_paths = [
        "/app/data/notes/.gemini_api_key",
        os.path.join(os.path.dirname(__file__), "..", "..", ".gemini_api_key")
    ]
    try:
        from app.config import NOTES_DIR
        if NOTES_DIR:
            candidate_paths.insert(0, os.path.join(NOTES_DIR, ".gemini_api_key"))
    except Exception:
        pass

    for cp in candidate_paths:
        if os.path.exists(cp):
            try:
                with open(cp, "r", encoding="utf-8") as f:
                    k = f.read().strip()
                    if k:
                        return k
            except Exception:
                pass

    return ""

def save_gemini_api_key(api_key: str) -> bool:
    """Saves Gemini API key to persistent server storage if available."""
    clean = api_key.strip()
    if not clean:
        return False
    target_paths = ["/app/data/notes/.gemini_api_key"]
    try:
        from app.config import NOTES_DIR
        if NOTES_DIR and os.path.exists(NOTES_DIR):
            target_paths.insert(0, os.path.join(NOTES_DIR, ".gemini_api_key"))
    except Exception:
        pass

    for tp in target_paths:
        try:
            os.makedirs(os.path.dirname(tp), exist_ok=True)
            with open(tp, "w", encoding="utf-8") as f:
                f.write(clean)
            return True
        except Exception as e:
            logger.warning(f"Could not save Gemini key to {tp}: {e}")
    return False

def normalize_model_name(model_name: Optional[str]) -> str:
    """Strictly enforces the gemini-3.8-flash-high model."""
    return "gemini-3.8-flash-high"

def call_gemini_api(
    contents: List[Dict[str, Any]],
    api_key: str,
    model: str = "gemini-3.8-flash-high",
    system_instruction: Optional[str] = None,
    response_json: bool = False
) -> str:
    """
    Direct HTTPS REST call to Google Gemini API (no external heavy SDK needed).
    Strictly uses the gemini-3.8-flash-high endpoint with no fallbacks.
    """
    key = resolve_gemini_api_key(api_key)
    if not key:
        raise ValueError("Gemini API key is required. Please add your key in the AI Setup modal or set GEMINI_API_KEY.")

    target_model = normalize_model_name(model)

    payload: Dict[str, Any] = {
        "contents": contents,
        "generationConfig": {
            "temperature": 0.2,
            "maxOutputTokens": 8192
        }
    }
    if response_json:
        payload["generationConfig"]["responseMimeType"] = "application/json"

    if system_instruction:
        payload["systemInstruction"] = {
            "parts": [{"text": system_instruction}]
        }

    url = f"https://generativelanguage.googleapis.com/v1beta/models/{target_model}:generateContent?key={key}"
    
    try:
        resp = requests.post(url, json=payload, headers={"Content-Type": "application/json"}, timeout=120)
        
        if resp.status_code == 200:
            data = resp.json()
            candidates = data.get("candidates", [])
            if not candidates:
                raise ValueError("No response generated by Gemini model.")
            parts = candidates[0].get("content", {}).get("parts", [])
            full_text = "".join([p.get("text", "") for p in parts])
            return full_text
            
        elif resp.status_code in [400, 404]:
            raise ValueError(f"Model '{target_model}' request failed ({resp.status_code}): {resp.text}")
        elif resp.status_code == 403:
            raise ValueError("Gemini API key is invalid or unauthorized. Please verify your Google AI Studio key.")
        elif resp.status_code == 429:
            raise ValueError("Gemini API rate limit exceeded. Please wait a moment before trying again.")
        else:
            raise ValueError(f"Gemini API error ({resp.status_code}): {resp.text}")
            
    except requests.exceptions.Timeout:
        raise ValueError("Gemini API request timed out. Please try again.")
    except requests.exceptions.RequestException as e:
        raise ValueError(f"Failed to generate content with Gemini. Network error: {str(e)}")


def test_gemini_connection(api_key: str, model: str = "gemini-3.8-flash-high") -> Dict[str, Any]:
    """Tests if the Gemini API key and model work properly."""
    try:
        contents = [{"parts": [{"text": "Reply with 'DevOps Hub AI is connected successfully!'"}]}]
        reply = call_gemini_api(contents, api_key=api_key, model=model)
        return {
            "status": "success",
            "message": reply.strip(),
            "model": normalize_model_name(model)
        }
    except Exception as e:
        return {
            "status": "error",
            "message": str(e)
        }

def polish_and_review_text(raw_text: str, api_key: str = "", model: str = "gemini-3.8-flash-high") -> Dict[str, Any]:
    """
    Grammar review, correction, scenario parsing, and structured question extraction from raw user text.
    Auto-generates production-grade answers labeled as [AI-Generated Answer].
    If instructor suggestions or answers are present, AI incorporates and elaborates on them.
    Preserves original text untouched and returns both.
    """
    system_instruction = (
        "You are an expert DevOps lead architect, interview coach, and technical editor. "
        "Review the provided DevOps interview questions, scenario notes, and answers.\n"
        "CRITICAL REQUIREMENTS:\n"
        "1. Recognize scenario-based questions: Detect Scenario Context, architecture flows (e.g. Internet -> LB -> Ingress -> Services), Primary Question, Sub-Questions, and Instructor's Suggestions/Answers.\n"
        "2. Question structure: For each question, extract:\n"
        "   - 'question': Main question title/prompt. If scenario context is present, format it clearly with markdown (e.g. '### Scenario Context:\\n...\\n\\n### Primary Question:\\n...').\n"
        "   - 'sub_questions': list of follow-up questions or sub-questions.\n"
        "   - 'suggestions': instructor's hints, root-cause notes, or suggestions.\n"
        "   - 'categories': relevant DevOps categories (Kubernetes, Microservices, Networking, Docker, Linux, Shell script, Jenkins, CI/CD, AWS, Terraform, Ansible, Jira, Scrum, Agile, Monitoring tools, Python, Azure, AI tool).\n"
        "   - 'difficulty': 'Basic', 'Moderate', or 'Advanced'.\n"
        "3. Answer generation (MANDATORY):\n"
        "   - You MUST auto-generate a comprehensive, in-depth, production-grade DevOps answer with exact CLI commands (e.g., kubectl get endpoints, kubectl describe, kubectl logs), configuration snippets, root cause troubleshooting, and resolution steps.\n"
        "   - The answer MUST start with '💡 **[AI-Generated Answer]**' (or '💡 **[AI-Generated Answer - Elaborated from Instructor's Suggestion]**').\n"
        "   - If instructor suggestions or partial answers are provided in the input, you MUST fully synthesize and elaborate on them into the detailed answer.\n"
        "   - If NO answer was provided in the input, generate a complete production-grade answer.\n"
        "Format any bash scripts, commands, and Kubernetes manifests cleanly with markdown backticks."
    )

    prompt = f"""
Given the following raw interview notes/questions:
\"\"\"{raw_text}\"\"\"

Provide your response as a valid JSON object with the exact keys:
1. "polished_text": A cleanly formatted, grammatically polished markdown version of the complete text.
2. "questions": An array of question objects, each with:
   - "question": string (the question title, incorporating scenario context if provided)
   - "sub_questions": list of strings (any sub-questions or follow-up prompts)
   - "answer": string (the refined, production-grade DevOps answer, starting with '💡 **[AI-Generated Answer]**')
   - "suggestions": string (instructor's suggestions/hints, or empty string)
   - "categories": list of strings (e.g. Kubernetes, Microservices, Networking, Docker, AWS, Linux, CI/CD, etc.)
   - "difficulty": string ("Basic", "Moderate", or "Advanced")
"""

    contents = [{"parts": [{"text": prompt}]}]
    response_text = call_gemini_api(
        contents,
        api_key=api_key,
        model=model,
        system_instruction=system_instruction,
        response_json=True
    )

    def ensure_ai_label_on_questions(q_list: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        for q in q_list:
            ans = q.get("answer", "").strip()
            if not ans:
                ans = "💡 **[AI-Generated Answer]**\n\nTo be reviewed / prepared with production guidelines."
            elif not ("[AI-Generated Answer]" in ans or "AI-Generated" in ans):
                ans = f"💡 **[AI-Generated Answer]**\n\n{ans}"
            q["answer"] = ans
        return q_list

    try:
        data = json.loads(response_text)
        return {
            "status": "success",
            "original_text": raw_text,
            "polished_text": data.get("polished_text", raw_text),
            "questions": ensure_ai_label_on_questions(data.get("questions", []))
        }
    except Exception:
        # Fallback if json parse fails
        cleaned_json = re.sub(r'^```json\s*', '', response_text.strip(), flags=re.MULTILINE)
        cleaned_json = re.sub(r'```$', '', cleaned_json.strip(), flags=re.MULTILINE)
        try:
            data = json.loads(cleaned_json)
            return {
                "status": "success",
                "original_text": raw_text,
                "polished_text": data.get("polished_text", raw_text),
                "questions": ensure_ai_label_on_questions(data.get("questions", []))
            }
        except Exception:
            return {
                "status": "partial",
                "original_text": raw_text,
                "polished_text": response_text,
                "questions": []
            }

def extract_qa_from_transcript_text(transcript_text: str, api_key: str = "", model: str = "gemini-3.8-flash-high") -> Dict[str, Any]:
    """
    Extracts all questions, sub-questions, and instructor suggestions from a transcript.
    Uses the user's specific prompt requirement:
    'I have the Qa transcript. Extract all question asked by instructor and if there are any suggestion/answer given by the instructor, include that. Don't miss any questions, even the sub questions to it. I repeat, don't miss any questions.'
    """
    system_instruction = (
        "You are an expert DevOps technical interview analyzer. "
        "Your task is to analyze interview audio/video transcripts and extract every single question, "
        "sub-question, and instructor suggestion without omitting anything. "
        "Always respond with a strict valid JSON object."
    )

    user_core_prompt = (
        "I have the Qa transcript. Extract all question asked by instructor and if there are any suggestion/answer "
        "given by the instructor, include that. Don't miss any questions, even the sub questions to it. "
        "I repeat, don't miss any questions."
    )

    full_prompt = f"""
{user_core_prompt}

Transcript content:
\"\"\"{transcript_text}\"\"\"

Return a valid JSON object with the following schema:
{{
  "interview_summary": "Brief 2-3 sentence overview of technologies and topics covered",
  "questions": [
    {{
      "question": "Exact question asked by instructor/interviewer",
      "sub_questions": ["Follow-up question 1", "Sub-question 2"],
      "answer": "Candidate or instructor answer given in the conversation, or recommended answer if candidate answered incompletely",
      "suggestions": "Any advice, suggestions, best practices, or corrections provided by the instructor",
      "categories": ["Linux", "Docker", "Kubernetes", "AWS", ...],
      "difficulty": "Moderate"
    }}
  ]
}}
"""

    contents = [{"parts": [{"text": full_prompt}]}]
    response_text = call_gemini_api(
        contents,
        api_key=api_key,
        model=model,
        system_instruction=system_instruction,
        response_json=True
    )

    try:
        data = json.loads(response_text)
    except Exception:
        cleaned_json = re.sub(r'^```json\s*', '', response_text.strip(), flags=re.MULTILINE)
        cleaned_json = re.sub(r'```$', '', cleaned_json.strip(), flags=re.MULTILINE)
        data = json.loads(cleaned_json)

    return {
        "status": "success",
        "transcript": transcript_text,
        "summary": data.get("interview_summary", ""),
        "questions": data.get("questions", []),
        "count": len(data.get("questions", []))
    }

def fetch_youtube_subtitles_pure_python(video_id: str) -> str:
    """
    Fetches YouTube captions/transcripts directly using YouTube's timedtext/caption tracks
    without needing external binaries like yt-dlp.
    """
    watch_url = f"https://www.youtube.com/watch?v={video_id}"
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
        "Accept-Language": "en-US,en;q=0.9"
    }

    try:
        resp = requests.get(watch_url, headers=headers, timeout=15)
        if resp.status_code != 200:
            return ""
        html = resp.text

        # Search for captionTracks inside playerResponse
        caption_match = re.search(r'"captionTracks":\s*(\[[^\]]+\])', html)
        if not caption_match:
            return ""

        tracks_json = caption_match.group(1)
        tracks = json.loads(tracks_json)
        if not tracks:
            return ""

        # Prioritize English track
        selected_track = None
        for t in tracks:
            lang = t.get("languageCode", "").lower()
            if lang.startswith("en"):
                selected_track = t
                break
        if not selected_track:
            selected_track = tracks[0]

        base_url = selected_track.get("baseUrl")
        if not base_url:
            return ""

        # Fetch caption XML / JSON
        caption_resp = requests.get(base_url, headers=headers, timeout=15)
        if caption_resp.status_code != 200:
            return ""

        caption_xml = caption_resp.text
        # Parse XML text segments
        lines = []
        # Matches <text start="12.34" dur="2.5">Content</text>
        segments = re.findall(r'<text start="([\d\.]+)"[^>]*>(.*?)</text>', caption_xml)
        for start_sec, text in segments:
            # Clean HTML entities
            clean_text = text.replace("&amp;", "&").replace("&quot;", '"').replace("&#39;", "'").replace("&lt;", "<").replace("&gt;", ">").strip()
            # Convert start seconds to mm:ss
            try:
                sec = float(start_sec)
                mins = int(sec // 60)
                rem_sec = int(sec % 60)
                ts = f"{mins:02d}:{rem_sec:02d}"
            except Exception:
                ts = ""
            if clean_text:
                if ts:
                    lines.append(f"[{ts}] {clean_text}")
                else:
                    lines.append(clean_text)

        return "\n".join(lines)
    except Exception as e:
        logger.warning(f"Could not scrape YouTube subtitles: {e}")
        return ""

def extract_youtube_video_id(url: str) -> Optional[str]:
    """Extracts the YouTube 11-character video ID from multiple URL formats."""
    patterns = [
        r'(?:v=|\/)([0-9A-Za-z_-]{11}).*',
        r'youtu\.be\/([0-9A-Za-z_-]{11})',
        r'youtube\.com\/embed\/([0-9A-Za-z_-]{11})',
        r'youtube\.com\/shorts\/([0-9A-Za-z_-]{11})'
    ]
    for p in patterns:
        m = re.search(p, url)
        if m:
            return m.group(1)
    return None

def process_youtube_interview(youtube_url: str, api_key: str = "", model: str = "gemini-3.8-flash-high") -> Dict[str, Any]:
    """
    Extracts transcript from a YouTube URL and processes all questions and suggestions using Gemini.
    """
    vid_id = extract_youtube_video_id(youtube_url)
    if not vid_id:
        raise ValueError("Invalid YouTube URL. Please provide a valid YouTube watch, short, or share link.")

    transcript = fetch_youtube_subtitles_pure_python(vid_id)

    if not transcript:
        # If public subtitles are not scraped, ask Gemini using YouTube URL reference directly
        key = resolve_gemini_api_key(api_key)
        if not key:
            raise ValueError("YouTube captions could not be fetched automatically and no Gemini API key is configured.")

        prompt = (
            f"Please analyze the technical DevOps interview from this YouTube video: {youtube_url}.\n"
            "I have the Qa transcript or video. Extract all question asked by instructor and if there are any suggestion/answer given by the instructor, include that. "
            "Don't miss any questions, even the sub questions to it. I repeat, don't miss any questions.\n"
            "Also generate a complete transcript of the conversation."
        )
        contents = [{"parts": [{"text": prompt}]}]
        try:
            resp_text = call_gemini_api(contents, api_key=api_key, model=model)
            return {
                "status": "success",
                "source_type": "youtube",
                "youtube_url": youtube_url,
                "transcript": resp_text,
                "questions": [],
                "note": "Extracted via Gemini YouTube multimodal analysis"
            }
        except Exception as e:
            raise ValueError(f"Could not retrieve YouTube transcript. The video may not have English captions available. Error: {e}")

    # Process extracted transcript
    res = extract_qa_from_transcript_text(transcript, api_key=api_key, model=model)
    res["source_type"] = "youtube"
    res["youtube_url"] = youtube_url
    return res

def upload_file_to_gemini_files_api(media_bytes: bytes, mime_type: str, api_key: str) -> str:
    """
    Uploads large media (audio/video > 20MB) to Google Gemini Files API.
    Google automatically removes these files after 48 hours. Zero server disk storage used.
    """
    key = resolve_gemini_api_key(api_key)
    if not key:
        raise ValueError("Gemini API key is required.")

    upload_url = f"https://generativelanguage.googleapis.com/upload/v1beta/files?key={key}"
    num_bytes = len(media_bytes)

    # 1. Initiating Resumable Upload
    init_headers = {
        "X-Goog-Upload-Protocol": "resumable",
        "X-Goog-Upload-Command": "start",
        "X-Goog-Upload-Header-Content-Length": str(num_bytes),
        "X-Goog-Upload-Header-Content-Type": mime_type,
        "Content-Type": "application/json"
    }
    init_data = {"file": {"display_name": "ephemeral_interview_media"}}

    init_resp = requests.post(upload_url, headers=init_headers, json=init_data, timeout=30)
    if init_resp.status_code != 200:
        raise ValueError(f"Failed to initiate Gemini file upload: {init_resp.text}")

    upload_location = init_resp.headers.get("X-Goog-Upload-URL")
    if not upload_location:
        raise ValueError("No upload location returned by Google Gemini Files API.")

    # 2. Upload Bytes
    upload_headers = {
        "Content-Length": str(num_bytes),
        "X-Goog-Upload-Offset": "0",
        "X-Goog-Upload-Command": "upload, finalize"
    }
    upload_resp = requests.post(upload_location, headers=upload_headers, data=media_bytes, timeout=300)
    if upload_resp.status_code != 200:
        raise ValueError(f"Failed to upload media data to Gemini: {upload_resp.text}")

    res_json = upload_resp.json()
    file_uri = res_json.get("file", {}).get("uri")
    if not file_uri:
        raise ValueError("Google Gemini Files API did not return a valid file URI.")

    return file_uri

def process_ephemeral_media(
    media_bytes: bytes,
    mime_type: str,
    api_key: str = "",
    model: str = "gemini-3.8-flash-high"
) -> Dict[str, Any]:
    """
    Transcribes audio/video completely in-memory or via Google Files API,
    extracts all questions, sub-questions, and instructor suggestions,
    and returns transcript + questions without persisting any media to server storage.
    """
    key = resolve_gemini_api_key(api_key)
    if not key:
        raise ValueError("Gemini API key is required to process audio/video recordings.")

    system_instruction = (
        "You are an expert DevOps technical interview transcriber and analyst. "
        "1. First, provide a thorough, complete, verbatim transcript of the entire interview audio/video.\n"
        "2. Then, follow this rule: 'Extract all question asked by instructor and if there are any suggestion/answer given by the instructor, include that. Don't miss any questions, even the sub questions to it. I repeat, don't miss any questions.'\n"
        "Return a JSON object with 'transcript' and 'questions' array."
    )

    prompt_text = (
        "Analyze this interview recording.\n"
        "Generate the complete transcript, then extract all questions asked by the instructor, "
        "including all sub-questions, candidate/instructor answers, and any suggestions or advice given by the instructor.\n\n"
        "Return a JSON object with the structure:\n"
        "{\n"
        "  \"transcript\": \"Full verbatim timestamped transcript of the interview...\",\n"
        "  \"interview_summary\": \"Summary of topics\",\n"
        "  \"questions\": [\n"
        "    {\n"
        "      \"question\": \"Main question asked\",\n"
        "      \"sub_questions\": [\"Sub-question 1\"],\n"
        "      \"answer\": \"Answer discussed in interview\",\n"
        "      \"suggestions\": \"Interviewer suggestions or corrections\",\n"
        "      \"categories\": [\"Linux\", \"Docker\", ...],\n"
        "      \"difficulty\": \"Moderate\"\n"
        "    }\n"
        "  ]\n"
        "}"
    )

    parts: List[Dict[str, Any]] = []

    # If small file (<= 20MB), pass inline base64
    if len(media_bytes) <= 20 * 1024 * 1024:
        b64_data = base64.b64encode(media_bytes).decode("utf-8")
        parts.append({
            "inlineData": {
                "mimeType": mime_type,
                "data": b64_data
            }
        })
    else:
        # Upload to Gemini Files API (ephemeral Google cloud buffer, deleted in 48 hrs)
        file_uri = upload_file_to_gemini_files_api(media_bytes, mime_type, key)
        parts.append({
            "fileData": {
                "mimeType": mime_type,
                "fileUri": file_uri
            }
        })

    parts.append({"text": prompt_text})
    contents = [{"parts": parts}]

    resp_text = call_gemini_api(
        contents,
        api_key=key,
        model=model,
        system_instruction=system_instruction,
        response_json=True
    )

    try:
        data = json.loads(resp_text)
    except Exception:
        cleaned_json = re.sub(r'^```json\s*', '', resp_text.strip(), flags=re.MULTILINE)
        cleaned_json = re.sub(r'```$', '', cleaned_json.strip(), flags=re.MULTILINE)
        data = json.loads(cleaned_json)

    return {
        "status": "success",
        "source_type": "video_upload",
        "transcript": data.get("transcript", ""),
        "summary": data.get("interview_summary", ""),
        "questions": data.get("questions", []),
        "count": len(data.get("questions", []))
    }

def process_bulk_interview_files(
    file_data_list: List[Dict[str, str]],
    source_comment: str = "whatsapp",
    api_key: str = "",
    model: str = "gemini-3.8-flash-high"
) -> Dict[str, Any]:
    """
    Parses multiple raw text/markdown interview files uploaded by Admin.
    Extracts companies, rounds, dates, categories, questions, sub-questions, and instructor suggestions.
    Auto-generates elaborated AI answers labeled with [AI-Generated Answer].
    Builds a single unified markdown document formatted for the Old Interview Questions repository.
    """
    clean_source = re.sub(r'^(from\s*:\s*|from\s+)', '', (source_comment or "").strip(), flags=re.IGNORECASE).strip()
    if not clean_source:
        clean_source = "uploaded notes"

    system_instruction = (
        "You are an expert DevOps Lead Architect, Senior Interviewer, and Technical Documentation Specialist. "
        "You are provided with contents of multiple interview text or markdown files collected from various candidates/sources. "
        "Each file may contain interview questions, dates, company names, round names, scenario contexts, and instructor suggestions.\n"
        "YOUR CORE TASKS:\n"
        "1. Extract ALL questions from all files without skipping any question or sub-question.\n"
        "2. Identify the Company name and Round name (e.g. 'L1', 'Technical Discussion 1', 'Assessment', 'Screening', 'Managerial') for each question. If company name is not explicit in the text, deduce it from context or group under 'General DevOps Interviews'.\n"
        "3. Identify the interview Date and Category (CI/CD, DOCKER, KUBERNETES, TERRAFORM, AWS, LINUX, SHELL SCRIPT, ANSIBLE, NETWORKING, MICROSERVICES, MONITORING, GIT, PYTHON, AZURE, GENERAL).\n"
        "4. Auto-generate comprehensive, production-grade DevOps answers for EVERY question:\n"
        "   - The answer MUST start with '💡 **[AI-Generated Answer]**'.\n"
        "   - If instructor suggestions or answers are present, incorporate and elaborate on them into a detailed step-by-step troubleshooting guide or explanation with exact commands and manifests.\n"
        "   - If no answer was provided, write a complete, high-quality production answer.\n"
        "5. Compile all questions hierarchically (Company -> Round -> Category -> Questions) into a single, beautifully structured Markdown document matching the exact schema:\n\n"
        "# DevOps Interview Questions (from " + clean_source + ")\n\n"
        "<details open>\n"
        "<summary><h2>🏢 Company Name</h2></summary>\n\n"
        "<details open>\n"
        "<summary><h3>Round Name</h3></summary>\n\n"
        "*Date: DD-MMM-YYYY*\n\n"
        "#### 【 CATEGORY 】\n\n"
        "<details>\n"
        "<summary><strong>● Question Title / Prompt</strong></summary>\n\n"
        "**Scenario Context:** (if applicable)\n"
        "Context details\n\n"
        "**Sub-Questions:** (if applicable)\n"
        "- Sub question 1\n\n"
        "**Instructor's Suggestion / Hints:** (if applicable)\n"
        "Instructor suggestion\n\n"
        "**Answer:**\n"
        "💡 **[AI-Generated Answer]**\n"
        "Detailed production-grade answer...\n"
        "</details>\n\n"
        "</details>\n"
        "</details>\n\n"
        "6. Return strict JSON with keys:\n"
        "- 'markdown_content': string (the full generated markdown)\n"
        "- 'companies_count': int\n"
        "- 'rounds_count': int\n"
        "- 'questions_count': int\n"
        "- 'companies': list of string company names\n"
        "- 'categories': list of string categories\n"
    )

    file_blocks = []
    for idx, f_item in enumerate(file_data_list, 1):
        fname = f_item.get("filename", f"file_{idx}.txt")
        fcontent = f_item.get("content", "")
        file_blocks.append(f"=== FILE {idx}: {fname} ===\n{fcontent}\n=== END FILE {idx} ===")

    combined_text = "\n\n".join(file_blocks)

    prompt = f"""
Files Origin / Comment: {clean_source}
Total uploaded files: {len(file_data_list)}

Uploaded Files:
\"\"\"
{combined_text}
\"\"\"

Please process and synthesize all interview questions into a single cohesive Markdown document with production-grade AI answers labeled with 💡 **[AI-Generated Answer]**, and return the strict JSON object.
"""

    contents = [{"parts": [{"text": prompt}]}]
    response_text = call_gemini_api(
        contents,
        api_key=api_key,
        model=model,
        system_instruction=system_instruction,
        response_json=True
    )

    try:
        data = json.loads(response_text)
    except Exception:
        cleaned_json = re.sub(r'^```json\s*', '', response_text.strip(), flags=re.MULTILINE)
        cleaned_json = re.sub(r'```$', '', cleaned_json.strip(), flags=re.MULTILINE)
        try:
            data = json.loads(cleaned_json)
        except Exception:
            data = {
                "markdown_content": response_text,
                "companies_count": 1,
                "rounds_count": 1,
                "questions_count": 1,
                "companies": ["DevOps Interviews"],
                "categories": ["General"]
            }

    md_content = data.get("markdown_content", "")
    if not md_content or len(md_content) < 50:
        md_content = f"# DevOps Interview Questions (from {clean_source})\n\n" + response_text

    return {
        "status": "success",
        "markdown_content": md_content,
        "companies_count": data.get("companies_count", len(data.get("companies", []))),
        "rounds_count": data.get("rounds_count", 1),
        "questions_count": data.get("questions_count", 0),
        "companies": data.get("companies", []),
        "categories": data.get("categories", [])
    }