"""
DevOps Knowledge Hub - Gemini AI Engine
Integrates Google Gemini 3.8 Flash High exclusively for:
1. Interview Transcript Generation from Audio & Video (Client-side / Ephemeral, zero server disk storage)
2. YouTube Video Transcript & Q&A Extraction
3. Complete Question, Sub-question, and Instructor Suggestion Extraction
4. AI Grammar Review & Text Polish (with Original Raw Text Preservation)
"""

import os
import re
import json
import base64
import logging
import urllib.parse
from typing import Dict, Any, List, Optional
import requests

logger = logging.getLogger("GeminiAIEngine")

# Supported models - strictly limited to 3.8 flash high
DEFAULT_MODELS = [
    "gemini-3.8-flash-high"
]

def resolve_gemini_api_key(client_key: Optional[str] = None) -> str:
    """
    Resolves the Gemini API key from:
    1. Client-supplied key (via header or request body)
    2. Server environment variable GEMINI_API_KEY
    3. Persistent token file on server (/app/data/notes/.gemini_api_key)
    """
    if client_key and client_key.strip():
        return client_key.strip()

    env_key = os.getenv("GEMINI_API_KEY", "").strip()
    if env_key:
        return env_key

    # Check file locations
    candidate_paths = [
        "/app/data/notes/.gemini_api_key",
        os.path.join(os.path.dirname(__file__), "..", "..", ".gemini_api_key")
    ]
    try:
        from app.config import NOTES_DIR
        if NOTES_DIR:
            candidate_paths.insert(0, os.path.join(NOTES_DIR, ".gemini_api_key"))
    except Exception:
        pass

    for cp in candidate_paths:
        if os.path.exists(cp):
            try:
                with open(cp, "r", encoding="utf-8") as f:
                    k = f.read().strip()
                    if k:
                        return k
            except Exception:
                pass

    return ""

def save_gemini_api_key(api_key: str) -> bool:
    """Saves Gemini API key to persistent server storage if available."""
    clean = api_key.strip()
    if not clean:
        return False
    target_paths = ["/app/data/notes/.gemini_api_key"]
    try:
        from app.config import NOTES_DIR
        if NOTES_DIR and os.path.exists(NOTES_DIR):
            target_paths.insert(0, os.path.join(NOTES_DIR, ".gemini_api_key"))
    except Exception:
        pass

    for tp in target_paths:
        try:
            os.makedirs(os.path.dirname(tp), exist_ok=True)
            with open(tp, "w", encoding="utf-8") as f:
                f.write(clean)
            return True
        except Exception as e:
            logger.warning(f"Could not save Gemini key to {tp}: {e}")
    return False

def normalize_model_name(model_name: Optional[str]) -> str:
    """Strictly enforces the gemini-3.8-flash-high model."""
    return "gemini-3.8-flash-high"

def call_gemini_api(
    contents: List[Dict[str, Any]],
    api_key: str,
    model: str = "gemini-3.8-flash-high",
    system_instruction: Optional[str] = None,
    response_json: bool = False
) -> str:
    """
    Direct HTTPS REST call to Google Gemini API (no external heavy SDK needed).
    Strictly uses the gemini-3.8-flash-high endpoint with no fallbacks.
    """
    key = resolve_gemini_api_key(api_key)
    if not key:
        raise ValueError("Gemini API key is required. Please add your key in the AI Setup modal or set GEMINI_API_KEY.")

    target_model = normalize_model_name(model)

    payload: Dict[str, Any] = {
        "contents": contents,
        "generationConfig": {
            "temperature": 0.2,
            "maxOutputTokens": 8192
        }
    }
    if response_json:
        payload["generationConfig"]["responseMimeType"] = "application/json"

    if system_instruction:
        payload["systemInstruction"] = {
            "parts": [{"text": system_instruction}]
        }

    url = f"https://generativelanguage.googleapis.com/v1beta/models/{target_model}:generateContent?key={key}"
    
    try:
        resp = requests.post(url, json=payload, headers={"Content-Type": "application/json"}, timeout=120)
        
        if resp.status_code == 200:
            data = resp.json()
            candidates = data.get("candidates", [])
            if not candidates:
                raise ValueError("No response generated by Gemini model.")
            parts = candidates[0].get("content", {}).get("parts", [])
            full_text = "".join([p.get("text", "") for p in parts])
            return full_text
            
        elif resp.status_code in [400, 404]:
            raise ValueError(f"Model '{target_model}' request failed ({resp.status_code}): {resp.text}")
        elif resp.status_code == 403:
            raise ValueError("Gemini API key is invalid or unauthorized. Please verify your Google AI Studio key.")
        elif resp.status_code == 429:
            raise ValueError("Gemini API rate limit exceeded. Please wait a moment before trying again.")
        else:
            raise ValueError(f"Gemini API error ({resp.status_code}): {resp.text}")
            
    except requests.exceptions.Timeout:
        raise ValueError("Gemini API request timed out. Please try again.")
    except requests.exceptions.RequestException as e:
        raise ValueError(f"Failed to generate content with Gemini. Network error: {str(e)}")


def test_gemini_connection(api_key: str, model: str = "gemini-3.8-flash-high") -> Dict[str, Any]:
    """Tests if the Gemini API key and model work properly."""
    try:
        contents = [{"parts": [{"text": "Reply with 'DevOps Hub AI is connected successfully!'"}]}]
        reply = call_gemini_api(contents, api_key=api_key, model=model)
        return {
            "status": "success",
            "message": reply.strip(),
            "model": normalize_model_name(model)
        }
    except Exception as e:
        return {
            "status": "error",
            "message": str(e)
        }

def polish_and_review_text(raw_text: str, api_key: str = "", model: str = "gemini-3.8-flash-high") -> Dict[str, Any]:
    """
    Grammar review, correction, and structured question extraction from raw user text.
    Preserves original text untouched and returns both.
    """
    system_instruction = (
        "You are an expert DevOps engineer and technical editor. "
        "Review the provided DevOps interview questions and answers. "
        "Fix all grammar, spelling, and phrasing issues while maintaining strict technical accuracy. "
        "Format any bash scripts, commands, and Kubernetes manifests cleanly with markdown backticks. "
        "Extract every question and sub-question into a structured JSON format."
    )

    prompt = f"""
Given the following raw interview notes/questions:
\"\"\"{raw_text}\"\"\"

Provide your response as a valid JSON object with the exact keys:
1. "polished_text": A cleanly formatted, grammatically polished markdown version of the complete text.
2. "questions": An array of question objects, each with:
   - "question": string (the main question title/text)
   - "sub_questions": list of strings (any sub-questions or follow-up prompts)
   - "answer": string (the refined, production-grade DevOps answer)
   - "suggestions": string (any tips, best practices, or feedback, or empty string)
   - "categories": list of strings (e.g. Linux, Shell script, jenkins, Github, Build tools, Docker, AWS, Kubernetes, terraform, Ansible, jira, scrum, Agile, Monitoring tools, python, Azure, AI tool)
   - "difficulty": string ("Basic", "Moderate", or "Advanced")
"""

    contents = [{"parts": [{"text": prompt}]}]
    response_text = call_gemini_api(
        contents,
        api_key=api_key,
        model=model,
        system_instruction=system_instruction,
        response_json=True
    )

    try:
        data = json.loads(response_text)
        return {
            "status": "success",
            "original_text": raw_text,
            "polished_text": data.get("polished_text", raw_text),
            "questions": data.get("questions", [])
        }
    except Exception:
        # Fallback if json parse fails
        cleaned_json = re.sub(r'^```json\s*', '', response_text.strip(), flags=re.MULTILINE)
        cleaned_json = re.sub(r'```$', '', cleaned_json.strip(), flags=re.MULTILINE)
        try:
            data = json.loads(cleaned_json)
            return {
                "status": "success",
                "original_text": raw_text,
                "polished_text": data.get("polished_text", raw_text),
                "questions": data.get("questions", [])
            }
        except Exception:
            return {
                "status": "partial",
                "original_text": raw_text,
                "polished_text": response_text,
                "questions": []
            }

def extract_qa_from_transcript_text(transcript_text: str, api_key: str = "", model: str = "gemini-3.8-flash-high") -> Dict[str, Any]:
    """
    Extracts all questions, sub-questions, and instructor suggestions from a transcript.
    Uses the user's specific prompt requirement:
    'I have the Qa transcript. Extract all question asked by instructor and if there are any suggestion/answer given by the instructor, include that. Don't miss any questions, even the sub questions to it. I repeat, don't miss any questions.'
    """
    system_instruction = (
        "You are an expert DevOps technical interview analyzer. "
        "Your task is to analyze interview audio/video transcripts and extract every single question, "
        "sub-question, and instructor suggestion without omitting anything. "
        "Always respond with a strict valid JSON object."
    )

    user_core_prompt = (
        "I have the Qa transcript. Extract all question asked by instructor and if there are any suggestion/answer "
        "given by the instructor, include that. Don't miss any questions, even the sub questions to it. "
        "I repeat, don't miss any questions."
    )

    full_prompt = f"""
{user_core_prompt}

Transcript content:
\"\"\"{transcript_text}\"\"\"

Return a valid JSON object with the following schema:
{{
  "interview_summary": "Brief 2-3 sentence overview of technologies and topics covered",
  "questions": [
    {{
      "question": "Exact question asked by instructor/interviewer",
      "sub_questions": ["Follow-up question 1", "Sub-question 2"],
      "answer": "Candidate or instructor answer given in the conversation, or recommended answer if candidate answered incompletely",
      "suggestions": "Any advice, suggestions, best practices, or corrections provided by the instructor",
      "categories": ["Linux", "Docker", "Kubernetes", "AWS", ...],
      "difficulty": "Moderate"
    }}
  ]
}}
"""

    contents = [{"parts": [{"text": full_prompt}]}]
    response_text = call_gemini_api(
        contents,
        api_key=api_key,
        model=model,
        system_instruction=system_instruction,
        response_json=True
    )

    try:
        data = json.loads(response_text)
    except Exception:
        cleaned_json = re.sub(r'^```json\s*', '', response_text.strip(), flags=re.MULTILINE)
        cleaned_json = re.sub(r'```$', '', cleaned_json.strip(), flags=re.MULTILINE)
        data = json.loads(cleaned_json)

    return {
        "status": "success",
        "transcript": transcript_text,
        "summary": data.get("interview_summary", ""),
        "questions": data.get("questions", []),
        "count": len(data.get("questions", []))
    }

def fetch_youtube_subtitles_pure_python(video_id: str) -> str:
    """
    Fetches YouTube captions/transcripts directly using YouTube's timedtext/caption tracks
    without needing external binaries like yt-dlp.
    """
    watch_url = f"https://www.youtube.com/watch?v={video_id}"
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
        "Accept-Language": "en-US,en;q=0.9"
    }

    try:
        resp = requests.get(watch_url, headers=headers, timeout=15)
        if resp.status_code != 200:
            return ""
        html = resp.text

        # Search for captionTracks inside playerResponse
        caption_match = re.search(r'"captionTracks":\s*(\[[^\]]+\])', html)
        if not caption_match:
            return ""

        tracks_json = caption_match.group(1)
        tracks = json.loads(tracks_json)
        if not tracks:
            return ""

        # Prioritize English track
        selected_track = None
        for t in tracks:
            lang = t.get("languageCode", "").lower()
            if lang.startswith("en"):
                selected_track = t
                break
        if not selected_track:
            selected_track = tracks[0]

        base_url = selected_track.get("baseUrl")
        if not base_url:
            return ""

        # Fetch caption XML / JSON
        caption_resp = requests.get(base_url, headers=headers, timeout=15)
        if caption_resp.status_code != 200:
            return ""

        caption_xml = caption_resp.text
        # Parse XML text segments
        lines = []
        # Matches <text start="12.34" dur="2.5">Content</text>
        segments = re.findall(r'<text start="([\d\.]+)"[^>]*>(.*?)</text>', caption_xml)
        for start_sec, text in segments:
            # Clean HTML entities
            clean_text = text.replace("&amp;", "&").replace("&quot;", '"').replace("&#39;", "'").replace("&lt;", "<").replace("&gt;", ">").strip()
            # Convert start seconds to mm:ss
            try:
                sec = float(start_sec)
                mins = int(sec // 60)
                rem_sec = int(sec % 60)
                ts = f"{mins:02d}:{rem_sec:02d}"
            except Exception:
                ts = ""
            if clean_text:
                if ts:
                    lines.append(f"[{ts}] {clean_text}")
                else:
                    lines.append(clean_text)

        return "\n".join(lines)
    except Exception as e:
        logger.warning(f"Could not scrape YouTube subtitles: {e}")
        return ""

def extract_youtube_video_id(url: str) -> Optional[str]:
    """Extracts the YouTube 11-character video ID from multiple URL formats."""
    patterns = [
        r'(?:v=|\/)([0-9A-Za-z_-]{11}).*',
        r'youtu\.be\/([0-9A-Za-z_-]{11})',
        r'youtube\.com\/embed\/([0-9A-Za-z_-]{11})',
        r'youtube\.com\/shorts\/([0-9A-Za-z_-]{11})'
    ]
    for p in patterns:
        m = re.search(p, url)
        if m:
            return m.group(1)
    return None

def process_youtube_interview(youtube_url: str, api_key: str = "", model: str = "gemini-3.8-flash-high") -> Dict[str, Any]:
    """
    Extracts transcript from a YouTube URL and processes all questions and suggestions using Gemini.
    """
    vid_id = extract_youtube_video_id(youtube_url)
    if not vid_id:
        raise ValueError("Invalid YouTube URL. Please provide a valid YouTube watch, short, or share link.")

    transcript = fetch_youtube_subtitles_pure_python(vid_id)

    if not transcript:
        # If public subtitles are not scraped, ask Gemini using YouTube URL reference directly
        key = resolve_gemini_api_key(api_key)
        if not key:
            raise ValueError("YouTube captions could not be fetched automatically and no Gemini API key is configured.")

        prompt = (
            f"Please analyze the technical DevOps interview from this YouTube video: {youtube_url}.\n"
            "I have the Qa transcript or video. Extract all question asked by instructor and if there are any suggestion/answer given by the instructor, include that. "
            "Don't miss any questions, even the sub questions to it. I repeat, don't miss any questions.\n"
            "Also generate a complete transcript of the conversation."
        )
        contents = [{"parts": [{"text": prompt}]}]
        try:
            resp_text = call_gemini_api(contents, api_key=api_key, model=model)
            return {
                "status": "success",
                "source_type": "youtube",
                "youtube_url": youtube_url,
                "transcript": resp_text,
                "questions": [],
                "note": "Extracted via Gemini YouTube multimodal analysis"
            }
        except Exception as e:
            raise ValueError(f"Could not retrieve YouTube transcript. The video may not have English captions available. Error: {e}")

    # Process extracted transcript
    res = extract_qa_from_transcript_text(transcript, api_key=api_key, model=model)
    res["source_type"] = "youtube"
    res["youtube_url"] = youtube_url
    return res

def upload_file_to_gemini_files_api(media_bytes: bytes, mime_type: str, api_key: str) -> str:
    """
    Uploads large media (audio/video > 20MB) to Google Gemini Files API.
    Google automatically removes these files after 48 hours. Zero server disk storage used.
    """
    key = resolve_gemini_api_key(api_key)
    if not key:
        raise ValueError("Gemini API key is required.")

    upload_url = f"https://generativelanguage.googleapis.com/upload/v1beta/files?key={key}"
    num_bytes = len(media_bytes)

    # 1. Initiating Resumable Upload
    init_headers = {
        "X-Goog-Upload-Protocol": "resumable",
        "X-Goog-Upload-Command": "start",
        "X-Goog-Upload-Header-Content-Length": str(num_bytes),
        "X-Goog-Upload-Header-Content-Type": mime_type,
        "Content-Type": "application/json"
    }
    init_data = {"file": {"display_name": "ephemeral_interview_media"}}

    init_resp = requests.post(upload_url, headers=init_headers, json=init_data, timeout=30)
    if init_resp.status_code != 200:
        raise ValueError(f"Failed to initiate Gemini file upload: {init_resp.text}")

    upload_location = init_resp.headers.get("X-Goog-Upload-URL")
    if not upload_location:
        raise ValueError("No upload location returned by Google Gemini Files API.")

    # 2. Upload Bytes
    upload_headers = {
        "Content-Length": str(num_bytes),
        "X-Goog-Upload-Offset": "0",
        "X-Goog-Upload-Command": "upload, finalize"
    }
    upload_resp = requests.post(upload_location, headers=upload_headers, data=media_bytes, timeout=300)
    if upload_resp.status_code != 200:
        raise ValueError(f"Failed to upload media data to Gemini: {upload_resp.text}")

    res_json = upload_resp.json()
    file_uri = res_json.get("file", {}).get("uri")
    if not file_uri:
        raise ValueError("Google Gemini Files API did not return a valid file URI.")

    return file_uri

def process_ephemeral_media(
    media_bytes: bytes,
    mime_type: str,
    api_key: str = "",
    model: str = "gemini-3.8-flash-high"
) -> Dict[str, Any]:
    """
    Transcribes audio/video completely in-memory or via Google Files API,
    extracts all questions, sub-questions, and instructor suggestions,
    and returns transcript + questions without persisting any media to server storage.
    """
    key = resolve_gemini_api_key(api_key)
    if not key:
        raise ValueError("Gemini API key is required to process audio/video recordings.")

    system_instruction = (
        "You are an expert DevOps technical interview transcriber and analyst. "
        "1. First, provide a thorough, complete, verbatim transcript of the entire interview audio/video.\n"
        "2. Then, follow this rule: 'Extract all question asked by instructor and if there are any suggestion/answer given by the instructor, include that. Don't miss any questions, even the sub questions to it. I repeat, don't miss any questions.'\n"
        "Return a JSON object with 'transcript' and 'questions' array."
    )

    prompt_text = (
        "Analyze this interview recording.\n"
        "Generate the complete transcript, then extract all questions asked by the instructor, "
        "including all sub-questions, candidate/instructor answers, and any suggestions or advice given by the instructor.\n\n"
        "Return a JSON object with the structure:\n"
        "{\n"
        "  \"transcript\": \"Full verbatim timestamped transcript of the interview...\",\n"
        "  \"interview_summary\": \"Summary of topics\",\n"
        "  \"questions\": [\n"
        "    {\n"
        "      \"question\": \"Main question asked\",\n"
        "      \"sub_questions\": [\"Sub-question 1\"],\n"
        "      \"answer\": \"Answer discussed in interview\",\n"
        "      \"suggestions\": \"Interviewer suggestions or corrections\",\n"
        "      \"categories\": [\"Linux\", \"Docker\", ...],\n"
        "      \"difficulty\": \"Moderate\"\n"
        "    }\n"
        "  ]\n"
        "}"
    )

    parts: List[Dict[str, Any]] = []

    # If small file (<= 20MB), pass inline base64
    if len(media_bytes) <= 20 * 1024 * 1024:
        b64_data = base64.b64encode(media_bytes).decode("utf-8")
        parts.append({
            "inlineData": {
                "mimeType": mime_type,
                "data": b64_data
            }
        })
    else:
        # Upload to Gemini Files API (ephemeral Google cloud buffer, deleted in 48 hrs)
        file_uri = upload_file_to_gemini_files_api(media_bytes, mime_type, key)
        parts.append({
            "fileData": {
                "mimeType": mime_type,
                "fileUri": file_uri
            }
        })

    parts.append({"text": prompt_text})
    contents = [{"parts": parts}]

    resp_text = call_gemini_api(
        contents,
        api_key=key,
        model=model,
        system_instruction=system_instruction,
        response_json=True
    )

    try:
        data = json.loads(resp_text)
    except Exception:
        cleaned_json = re.sub(r'^```json\s*', '', resp_text.strip(), flags=re.MULTILINE)
        cleaned_json = re.sub(r'```$', '', cleaned_json.strip(), flags=re.MULTILINE)
        data = json.loads(cleaned_json)

    return {
        "status": "success",
        "source_type": "video_upload",
        "transcript": data.get("transcript", ""),
        "summary": data.get("interview_summary", ""),
        "questions": data.get("questions", []),
        "count": len(data.get("questions", []))
    }