pipeline {
    agent any

    environment {
        AWS_ACCESS_KEY_ID     = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
        AWS_DEFAULT_REGION    = 'us-east-1'
    }

    stages {

        stage('Terraform Init') {
            steps {
                dir('Jenkins-Assignment/simple-terraform-integration-with-jenkins') {
                    sh 'terraform init'
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir('Jenkins-Assignment/simple-terraform-integration-with-jenkins') {
                    sh 'terraform plan'
                }
            }
        }

        stage('Manual Approval') {
            steps {
                input message: 'Review the Terraform Plan output above. Do you want to provision this infrastructure?',
                      ok: 'Yes, Apply'
            }
        }

        stage('Terraform Apply') {
            steps {
                dir('Jenkins-Assignment/simple-terraform-integration-with-jenkins') {
                    sh 'terraform apply --auto-approve'
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
