pipeline {
    agent any

    // Inject your cloud credentials securely as environment variables
    environment {
        AWS_ACCESS_KEY_ID     = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
        AWS_DEFAULT_REGION    = 'us-east-1'
    }

    stages {
        stage('Checkout Code') {
            steps {
                // Jenkins will automatically pull from the repo this Jenkinsfile is stored in
                checkout scm
            }
        }

        stage('Terraform Init') {
            steps {
                // dir is jenkins specific function. If you use cd, then it is shell specific, so you have to use: sh 'cd Jenkins-Assignment/simple-terraform-integration-with-jenkins'
                dir('Jenkins-Assignment/simple-terraform-integration-with-jenkins') {
                    sh 'terraform init'
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir('Jenkins-Assignment/simple-terraform-integration-with-jenkins') {
                    sh 'terraform plan'
                }
            }
        }

        stage('Manual Approval') {
            steps {
                input message: 'Review the Terraform Plan output above. Do you want to provision this infrastructure?', 
                      ok: 'Yes, Apply'
            }
        }

        stage('Terraform Apply') {
            steps {
                dir('Jenkins-Assignment/simple-terraform-integration-with-jenkins') {
                    sh 'terraform apply --auto-approve'
                }
            }
        }
        stage('Terraform Destroy') {
            steps {
                dir('Jenkins-Assignment/simple-terraform-integration-with-jenkins') {
                    sh 'terraform destroy --auto-approve'
                }
            }
        }
    }
    
    post {
        always {
            cleanWs()
        }
    }
}
